## System Parameters

VISIBILITY_THRESHOLD = 0.2
MIN_DETECTION_CONFIDENCE = 0.5
MIN_TRACKING_CONFIDENCE = 0.5

VIEWTYPE_THRSHOLD = 0.2  ## Side view check. Currently disabled.

## Feedback Parameters
BACK_ANGLE_THRESHOLD = 70
DEPTH_ANGLE_THRESHOLD = 25
KNEE_FORWARD_TOLERANCE = 0

